version: '3'

services:
  # Serviço para construir o aplicativo React
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app

  # Serviço para o servidor Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/build:/usr/share/nginx/html
    depends_on:
      - builder